#!/bin/sh
source ~/.bash_profile
cd /home/avaughan/rails_apps/gpx
git checkout db/schema.rb
git checkout master
git pull
bundle install --path vendor --without development test
RAILS_ENV=production bundle exec rake db:migrate
bundle exec rake tmp:clear
bundle exec rake assets:precompile
killall dispatch.fcgi
